### ISSUE TITLE
Issue when trying to use gulp to build code

### ISSUE THREAD

**Issue by tosha14990** [tom-daly/spfx-side-navigation#1]
I get this error when i am trying to use gulp to build the code

Error - [bump-revision-subtask] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
[10:06:24] Error - 'bump-revision-subtask' sub task errored after 16 ms 
 Callback must be a function
[10:06:24] 'default' errored after 106 ms
[10:06:24]
[10:06:25] ==================[ Finished ]==================
Error - [bump-revision-subtask] TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
Error - 'bump-revision-subtask' sub task errored after 16 ms 
 Callback must be a function

**Comment by tom-daly** [comment]
Thanks for the issue, this is related to the versioning script I wrote in the gulp task. it works with node version 8.16.0 and not the latest version.

I will take a look at re-writing it to support node 10 but as for now I recommend using node version manager (NVM) to use v8.1.6.0 to work around this.
