### ISSUE TITLE
Expanding Side-Nav is not working

### ISSUE THREAD

**Issue by sivanu137** [tom-daly/spfx-side-navigation#3]
![image](https://user-images.githubusercontent.com/31919925/95660971-14896980-0b49-11eb-952f-43a6ded788a5.png)

I  cannot able to expand the side nav, when I click the expand icon it is not showing all sub-links, instead of that it opens the link.

also how can I highlight the side nav if it is active. Example : if I'm in home page means how I can set css active , so that user can know where he is..

@tom-daly

**Comment by cryongen** [comment]
> ![image](https://user-images.githubusercontent.com/31919925/95660971-14896980-0b49-11eb-952f-43a6ded788a5.png)
> 
> I cannot able to expand the side nav, when I click the expand icon it is not showing all sub-links, instead of that it opens the link.
> 
> also how can I highlight the side nav if it is active. Example : if I'm in home page means how I can set css active , so that user can know where he is..
> 
> @tom-daly

Hello sivanu, set the home item url to empty maybe it works.

**Comment by sivanu137** [comment]
@cryongen Thanks buddy, setting the Home URL to empty does the magic which I wanted.
![image](https://user-images.githubusercontent.com/31919925/96661154-087f8200-1369-11eb-9ef6-2009f3b7e2bc.png)

One of my concerns got cleared, Now how we can set the 'Active' class and remove the class when we click the navigation. 
@tom-daly

**Comment by tom-daly** [comment]
sorry for the delay response. no url indicates an expandable section. let me look at active. 

I'm hearing you want the node highlighted if the url matches the url in the left nav.

**Comment by sivanu137** [comment]
Hi @tom-daly 
Yes, I want to set active if the URL matches the left nav. I'm adding an example snip with this.

![image](https://user-images.githubusercontent.com/31919925/96667320-7da58400-1376-11eb-8327-bd95659ada26.png)

If we do match our left nav URL with the current page URL how will it goes well, in the case of (For Ex: my left nav URL is 
https://abc.sharepoint.com/sites/example/_layouts/15/viewlsts.aspx   and my current page URL is https://abc.sharepoint.com/sites/example/_layouts/15/viewlsts.aspx?view=14    if we match these two URL'S, obviously it is going to be false only rite..? In this case how we can set active??).

**Comment by tom-daly** [comment]
I can make an update to match the full url, but the ? parameter would not match. I can also set it to ignore the ? portion. 
I'm going to investigate now.

**Comment by tom-daly** [comment]
this is a quick release. please check the the latest release. 

I'm check the url of the window and removing any thing after the ? symbol and comparing that to the nodes. If it's a match then i'm marking that as 'active' which is the same as hover. This will work on top level or sub nodes

**Comment by sivanu137** [comment]
@tom-daly 
Works pretty well . And I have found one more minor bug when using this, added the snap below for your convenience .

![image](https://user-images.githubusercontent.com/31919925/96839958-7b6f2280-1467-11eb-89b6-6b32445659c9.png)

Some times toggle icon is not loading properly, if I click on that toggle icon place then it shows the icon. 

This bug has been found when I keep navigating to some other pages. check this in your environment then you may come to see this minor issue.

Thanks @tom-daly

**Comment by tom-daly** [comment]
I have not seen that. I just added some code to force the icon init. That may help.
