### ISSUE TITLE
How I can deploy this solution again into the app catalog with a new Product ID?

### ISSUE THREAD

**Issue by sivanu137** [tom-daly/spfx-side-navigation#5]
@tom-daly 
I have already installed this solution into my tenant  level app catalogue . Now I wanted to upload this same solution with another name  into tenant level app catalogue without getting an error in app catalogue **(i.e.,) Solution with the same product it exists.**

How I can do this? for achieving this what are the steps I should follow?

Im a kind of newbie to this spfx.

Thanks in advance!!!

**Comment by tom-daly** [comment]
You could rebuild it with new id's and change the name of the solution. I have not tested this but this is what i would do. change the guids here in the picture and the name of the package. Use find and replace b/c the solution guid is also in another file and you want to change all references. rebuild the package and it should be seen as something different by SharePoint

![image](https://user-images.githubusercontent.com/9259305/102677364-0c186500-4170-11eb-852e-3e8cc556fd3f.png)

**Comment by sivanu137** [comment]
@tom-daly  To get guid what I should do?
I should create new solution just to take guid from the newly created solution?
